export default{
	entries : 10,
	search : '',
	users : {},
	user : {},
	properties : {},
	property : {},
	subscriptions : {},
	subscription : {},
	tasks : {},
	task : {},
	feedbacks : {},
	feedback : {},
	admins : {},
	admin : {},
	home : {},
	notification_count : 0,
	bell_notifications : [],
	notifications : {},
	owners : {},
}